### ISSUE TITLE
`/log --retrospective` option name might need a better name

### ISSUE THREAD

**Issue by bundacia** [LearnersGuild/game-cli#12]
#### Tension 1

It seems awkward that the `-r` option is used both to request the printing of all questions if no number is given and also to specify a specific question.

#### Tension 2

The full version of `-r` is `--reflection`, but it's actually naming the index of a specific reflection in the context of the retrospective survey. The name seems wrong.

#### Proposal (OND):

```
# print out the full retrospective survey
/log --retro 

# print out question 4 from the retrospective survey
/log --retro -n4

# answer question 4 from the retrospective survey
/log --retro -n4 "my answer!"
```

https://github.com/LearnersGuild/game-cli/blob/master/config/commands/log.yaml

**Comment by bundacia** [comment]
cc: @jeffreywescott

**Comment by tannerwelsh** [comment]
Thanks @bundacia - I agree that this can be confusing.

While your solution is a bit more verbose, which put me off at first, I realized that our option parser is actually intelligent to handle a terser form:

```
/log -rn 4 "answer"
```

Assuming two options `--retro / -r` and `--number / -n`.

Instead of a generic `n`, I'd rather use `q` for `question`.

That way, we can talk about **retrospectives** having a set of **questions**, with questions having **ids** that are used when providing a **response** to a question.

In the future, I could see us having other kinds of structured reflection/log types where we use the same question/id concept, but under a separate umbrella (i.e. not the retrospective).

For example, we could have a "ZPD" set of questions:

```
/log --zpd -q2 "Today I was put in my stretch zone by X activity because Y..."
```

**Comment by tannerwelsh** [comment]
PR forthcoming...

**Comment by jeffreywescott** [comment]
As predicted, @tannerwelsh goes "off into a corner", thinks things through, and comes out with the ultimate solution.
